### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by ytaylordev** [Adalab/modulo-3-evaluacion-intermedia-masarom#1]
Buen trabajo @masarom !

### Algunas pistas para acabarlo:

- [x] Comprueba que los `inputs` tengan algún valor cuando vas a añadir una nueva frase. 
- [x] Agrega manejo de errores al realizar la solicitud fetch.

> Recuerda: a medida que vayas realizando estas mejoras debes subirlas a la rama principal de este repo y marcarlas como realizadas en este issue. Si no, tu profe no sabrás que has realizado estas mejoras.

Si tienes cualquier duda, ¡avisa!

Al turrón!!!

**Comment by masarom** [comment]
Hola Yanelis! Acabo de subir los cambios a la rama `main` con las dos recomendaciones que me has dado. 

Muchas gracias por tus comentarios! 😄
